/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.ingesoft.standalone.gui.vista;

import javax.naming.NamingException;
import javax.swing.JOptionPane;

import co.edu.eam.ingesoft.avanzada.persistencia.entidades.Customer;
import co.edu.eam.ingesoft.standalone.gui.controlador.ControladorVentanaGestionCustomer;

/**
 *
 * @author Richard Vanegas
 */
public class VentanaGestionCustomer extends javax.swing.JFrame {

	/**
	 * controlador.
	 */
	private ControladorVentanaGestionCustomer controlador;

	/**
	 * Creates new form VentanaGestionCustomer
	 */
	public VentanaGestionCustomer() {
		try {
			controlador = new ControladorVentanaGestionCustomer();
		} catch (NamingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		initComponents();
		cargarComboTipoDocumento();
	}

	/**
	 * Metodo para limpiar los campos del formulario de crear customer
	 */
	public void limpiarCampos() {
		tfNombre.setText(null);
		tfApellido.setText(null);
		tfNumeroDocumento.setText(null);
	}

	/**
	 * Metodo para cargar el combobox de tipo de documento
	 */
	public void cargarComboTipoDocumento() {
		// for (String lista : TipoDocumentEnum.values()) {
		cbTipoDocumento.addItem("CEDULA");
		cbTipoDocumento.addItem("TARJETA DE IDENTIDAD");
		cbTipoDocumento.addItem("REGISTRO CIVIL");

		// }
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		tfNombre = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		tfApellido = new javax.swing.JTextField();
		tfNumeroDocumento = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		btnCrear = new javax.swing.JButton();
		btnBuscar = new javax.swing.JButton();
		btnEditar = new javax.swing.JButton();
		cbTipoDocumento = new javax.swing.JComboBox();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("Nombre:");

		jLabel2.setText("Apellido:");

		jLabel3.setText("Tipo documento:");

		jLabel4.setText("Numero documento:");

		jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		jLabel5.setText("GESTION CUSTOMER");

		btnCrear.setText("CREAR");
		btnCrear.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCrearActionPerformed(evt);
			}
		});

		btnBuscar.setText("BUSCAR");
		btnBuscar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnBuscarActionPerformed(evt);
			}
		});

		btnEditar.setText("EDITAR");
		btnEditar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnEditarActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
						.createSequentialGroup().addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
										.createSequentialGroup().addGap(46, 46, 46).addGroup(
												layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel1).addComponent(jLabel2)
														.addComponent(jLabel3).addComponent(jLabel4)))
								.addGroup(layout.createSequentialGroup().addGap(68, 68, 68).addComponent(btnCrear)))
						.addGap(29, 29, 29)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addGroup(layout.createSequentialGroup().addComponent(btnBuscar)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36,
														Short.MAX_VALUE)
												.addComponent(btnEditar))
										.addComponent(tfNombre).addComponent(tfApellido))
								.addComponent(tfNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 178,
										javax.swing.GroupLayout.PREFERRED_SIZE))
								.addComponent(cbTipoDocumento, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.PREFERRED_SIZE, 178,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(66, Short.MAX_VALUE))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								layout.createSequentialGroup()
										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 190,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(117, 117, 117)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(30, 30, 30)
				.addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(24, 24, 24)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel3)
						.addComponent(cbTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(21, 21, 21)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel4)
						.addComponent(tfNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel1)
						.addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel2)
						.addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(88, 88, 88).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(btnCrear).addComponent(btnBuscar).addComponent(btnEditar))
				.addGap(79, 79, 79)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCrearActionPerformed
		// TODO add your handling code here:
		try {
			if (tfNombre.getText().isEmpty() || tfApellido.getText().isEmpty()
					|| tfNumeroDocumento.getText().isEmpty()) {
				JOptionPane.showMessageDialog(null, "Debe completar todos los campos");
			} else {

				Customer c = new Customer();
				c.setName(tfNombre.getText());
				c.setLastName(tfApellido.getText());
				c.setIdNum(tfNumeroDocumento.getText());
				c.setIdType((String) cbTipoDocumento.getSelectedItem());
				limpiarCampos();
				controlador.crearCustomer(c);
				JOptionPane.showMessageDialog(null, "Se creo correctamente el customer");
			}

		} catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
		}

	}// GEN-LAST:event_btnCrearActionPerformed

	private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBuscarActionPerformed
		// TODO add your handling code here:
		try {
			System.out.println(cbTipoDocumento.getSelectedItem().toString());
			Customer cus = controlador.buscarCustomer(cbTipoDocumento.getSelectedItem().toString(),
					tfNumeroDocumento.getText());
			if (cus != null) {
				tfNombre.setText(cus.getName());
				tfApellido.setText(cus.getLastName());
			} else {
				JOptionPane.showMessageDialog(null, "No existe!!!!", "ERROR", JOptionPane.WARNING_MESSAGE);
			}

		} catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
		}
	}// GEN-LAST:event_btnBuscarActionPerformed

	private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEditarActionPerformed
		// TODO add your handling code here:

		try {

			Customer c = new Customer();
			c.setName(tfNombre.getText());
			c.setLastName(tfApellido.getText());
			// c.setIdNum(tfNumeroDocumento.getText());
			// c.setIdType(tfTipoDocumento.getText());

			controlador.editarCustomer(c);

		} catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
		}
	}// GEN-LAST:event_btnEditarActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnBuscar;
	private javax.swing.JButton btnCrear;
	private javax.swing.JButton btnEditar;
	private javax.swing.JComboBox<String> cbTipoDocumento;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JTextField tfApellido;
	private javax.swing.JTextField tfNombre;
	private javax.swing.JTextField tfNumeroDocumento;
	// End of variables declaration//GEN-END:variables
}
