/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.ingesoft.standalone.gui.vista;

import co.edu.eam.ingesoft.avanzada.persistencia.entidades.CreditCard;
import co.edu.eam.ingesoft.avanzada.persistencia.entidades.CreditCardConsume;
import co.edu.eam.ingesoft.avanzada.persistencia.entidades.CreditCardPaymentConsume;
import co.edu.eam.ingesoft.avanzada.persistencia.entidades.Customer;
import co.edu.eam.ingesoft.pa.negocio.excepciones.ExcepcionNegocio;
import co.edu.eam.ingesoft.standalone.gui.controlador.ControladorVentanaCreditCardPayment;
import co.edu.eam.ingesoft.standalone.gui.controlador.ControladorVentanaGestionCustomer;
import java.util.List;
import javax.naming.NamingException;
import javax.swing.JOptionPane;

/**
 *
 * @author lenovo
 */
public class VentanaCreditCardPayment extends javax.swing.JFrame {

	private ControladorVentanaGestionCustomer controladorCus;
	private ControladorVentanaCreditCardPayment controlador;

	/**
	 * Creates new form VentanaCreditCardPayment
	 */
	public VentanaCreditCardPayment() {
		try {
			controlador = new ControladorVentanaCreditCardPayment();
			controladorCus = new ControladorVentanaGestionCustomer();

		} catch (NamingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		initComponents();
		cargarComboTipoDocumento();
	}

	/**
	 * Metodo para cargar el combobox de tipo de documento
	 */
	public void cargarComboTipoDocumento() {
		cbTipoDocumento.addItem("CEDULA");
		cbTipoDocumento.addItem("TARJETA DE IDENTIDAD");
		cbTipoDocumento.addItem("REGISTRO CIVIL");
	}

	/**
	 * Metodo para cargar un combo con todas las tarjetas de credito de un
	 * cliente en especifico
	 * 
	 * @param c
	 *            cliente por el cual se listaran las tarjetas de credito
	 */
	public void cargarComboCuentas(Customer c) {
		cbNumeroTarjeta.removeAllItems();
		List<CreditCard> cred = controlador.listarTarjetasCliente(c);
		cbNumeroTarjeta.addItem("Seleccione una tarjeta");
		for (CreditCard lista : cred) {
			cbNumeroTarjeta.addItem(lista);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPCliente = new javax.swing.JPanel();
        tfNumeroDocumento = new javax.swing.JTextField();
        cbTipoDocumento = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnBuscarCliente = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfMontoPagar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfNumeroCuota = new javax.swing.JTextField();
        btnRealizarPago = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cbNumeroTarjeta = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        tfAdicionar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));

        jLabel15.setText("Tipo de documento:");

        jLabel16.setText("Numero de documento:");

        btnBuscarCliente.setText("BUSCAR");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPClienteLayout = new javax.swing.GroupLayout(jPCliente);
        jPCliente.setLayout(jPClienteLayout);
        jPClienteLayout.setHorizontalGroup(
            jPClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPClienteLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPClienteLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(tfNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPClienteLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(37, 37, 37)
                        .addComponent(cbTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnBuscarCliente)
                .addContainerGap())
        );
        jPClienteLayout.setVerticalGroup(
            jPClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPClienteLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnBuscarCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPClienteLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tfNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Realizar pago"));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("REALIZAR PAGO");

        jLabel1.setText("Monto a pagar:");

        jLabel2.setText("Numero de cuota:");

        btnRealizarPago.setText("REALIZAR PAGO");
        btnRealizarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarPagoActionPerformed(evt);
            }
        });

        jLabel3.setText("Numero de tarjeta:");

        cbNumeroTarjeta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbNumeroTarjetaItemStateChanged(evt);
            }
        });

        jLabel4.setText("Monto adicionado:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRealizarPago)
                .addGap(141, 141, 141))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(110, 110, 110)
                            .addComponent(jLabel8))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(cbNumeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(39, 39, 39)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(25, 25, 25)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfMontoPagar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfNumeroCuota, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addComponent(tfAdicionar))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cbNumeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfMontoPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNumeroCuota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(btnRealizarPago)
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void cbTransaccionPagarItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_cbTransaccionPagarItemStateChanged
		// TODO add your handling code here:
		try {
			if (cbNumeroTarjeta.getSelectedItem() !=null) {	
//				JOptionPane.showMessageDialog(null, "dont know", "ERROR", JOptionPane.ERROR_MESSAGE);
//			}else{
				tfMontoPagar.setText(String.valueOf(controlador.calcularCuotaTarjeta((CreditCard)cbNumeroTarjeta.getSelectedItem())));
			}
		} catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
		}
	}// GEN-LAST:event_cbTransaccionPagarItemStateChanged

	private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBuscarClienteActionPerformed
		// TODO add your handling code here:
		try {
			Customer cus = controladorCus.buscarCustomer((String) cbTipoDocumento.getSelectedItem(),
					tfNumeroDocumento.getText());
			if (cus != null) {

				cargarComboCuentas(cus);
				jPanel1.setVisible(true);

			} else {
				JOptionPane.showMessageDialog(null, "No existe!!!!", "ERROR", JOptionPane.WARNING_MESSAGE);
			}

		} catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
		}
	}// GEN-LAST:event_btnBuscarClienteActionPerformed

	private void cbNumeroTarjetaItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_cbNumeroTarjetaItemStateChanged
		// TODO add your handling code here:
		try {
			if (cbNumeroTarjeta.getSelectedIndex() != 0) {
				tfMontoPagar.setText(controlador.calcularCuotaTarjeta((CreditCard) cbNumeroTarjeta.getSelectedItem())+"");
		}
		} catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
		}
	}// GEN-LAST:event_cbNumeroTarjetaItemStateChanged

	private void btnRealizarPagoActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		
		try {
			double adicionar = 0;
			if (Double.parseDouble(tfMontoPagar.getText()) == 0) {
				JOptionPane.showMessageDialog(null, "No se han hecho transacciones con la tarjeta", "ERROR",
						JOptionPane.ERROR_MESSAGE);
			} else {
				if (!tfAdicionar.getText().isEmpty()) {
					adicionar = Double.parseDouble(tfAdicionar.getText());
				}
				CreditCard tarjeta = (CreditCard) cbNumeroTarjeta.getSelectedItem();
				controlador.crearCreditCardPayment(tarjeta.getNumber(), adicionar);
				JOptionPane.showMessageDialog(null, "Se ha registrado el pago", "Operación exitosa",
						JOptionPane.INFORMATION_MESSAGE);
			}
		} catch (ExcepcionNegocio e) {
			JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
		}
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnRealizarPago;
    private javax.swing.JComboBox cbNumeroTarjeta;
    private javax.swing.JComboBox<String> cbTipoDocumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPCliente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfAdicionar;
    private javax.swing.JTextField tfMontoPagar;
    private javax.swing.JTextField tfNumeroCuota;
    private javax.swing.JTextField tfNumeroDocumento;
    // End of variables declaration//GEN-END:variables
}
