/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.ingesoft.standalone.gui.vista;

import java.util.List;

import javax.naming.NamingException;
import javax.swing.JOptionPane;

import co.edu.eam.ingesoft.avanzada.persistencia.entidades.CreditCard;
import co.edu.eam.ingesoft.avanzada.persistencia.entidades.CreditCardConsume;
import co.edu.eam.ingesoft.avanzada.persistencia.entidades.Customer;
import co.edu.eam.ingesoft.standalone.gui.controlador.ControladorVentanaCreditCardConsume;
import co.edu.eam.ingesoft.standalone.gui.controlador.ControladorVentanaGestionCustomer;

/**
 *
 * @author Richard Vanegas
 */
public class VentanaCreditCardConsume extends javax.swing.JFrame {

	private ControladorVentanaCreditCardConsume controlador;
	private ControladorVentanaGestionCustomer controladorCus;

	/**
	 * Creates new form VentanaCreditCardConsume
	 */
	public VentanaCreditCardConsume() {
		try {
			controlador = new ControladorVentanaCreditCardConsume();
			controladorCus = new ControladorVentanaGestionCustomer();

		} catch (NamingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		initComponents();
		jTBPrincipal.setVisible(false);
		cargarComboTipoDocumento();
	}

	/**
	 * Metodo para cargar el combobox de tipo de documento
	 */
	public void cargarComboTipoDocumento() {
		cbTipoDocumento.addItem("CEDULA");
		cbTipoDocumento.addItem("TARJETA DE IDENTIDAD");
		cbTipoDocumento.addItem("REGISTRO CIVIL");
	}

	/**
	 * Metodo para cargar un combo con todas las tarjetas de credito de un
	 * cliente en especifico
	 * 
	 * @param c
	 *            cliente por el cual se listaran las tarjetas de credito
	 */
	public void cargarComboCuentas(Customer c) {
		cbNumeroTarjetaAvance.removeAllItems();
		cbNumeroTarjetaPedir.removeAllItems();
		List<CreditCard> cred = controlador.listarTarjetasCliente(c);
		cbNumeroTarjetaAvance.addItem("Seleccione una tarjeta");
		cbNumeroTarjetaPedir.addItem("Seleccione una tarjeta");
		for (CreditCard lista : cred) {
			cbNumeroTarjetaAvance.addItem(lista);
			cbNumeroTarjetaPedir.addItem(lista);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTBPrincipal = new javax.swing.JTabbedPane();
        jPConsumo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfMontoPedir = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfNumeroCuotasPedir = new javax.swing.JTextField();
        btnPedirConsumo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cbNumeroTarjetaPedir = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tfMontoAvance = new javax.swing.JTextField();
        cbNumeroTarjetaAvance = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnPedirAvance = new javax.swing.JButton();
        jPCliente = new javax.swing.JPanel();
        tfNumeroDocumento = new javax.swing.JTextField();
        cbTipoDocumento = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnBuscarCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Monto a pedir:");

        jLabel2.setText("Numero de cuotas:");

        btnPedirConsumo.setText("PEDIR CONSUMO");
        btnPedirConsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedirConsumoActionPerformed(evt);
            }
        });

        jLabel3.setText("Numero de tarjeta:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Peticion de consumo");

        javax.swing.GroupLayout jPConsumoLayout = new javax.swing.GroupLayout(jPConsumo);
        jPConsumo.setLayout(jPConsumoLayout);
        jPConsumoLayout.setHorizontalGroup(
            jPConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPConsumoLayout.createSequentialGroup()
                .addGroup(jPConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPConsumoLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addGroup(jPConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPConsumoLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbNumeroTarjetaPedir, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPConsumoLayout.createSequentialGroup()
                                    .addGroup(jPConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPConsumoLayout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(18, 18, 18))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPConsumoLayout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addGap(39, 39, 39)))
                                    .addGroup(jPConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tfMontoPedir)
                                        .addComponent(tfNumeroCuotasPedir, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPConsumoLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(btnPedirConsumo)))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        jPConsumoLayout.setVerticalGroup(
            jPConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPConsumoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbNumeroTarjetaPedir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfMontoPedir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNumeroCuotasPedir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btnPedirConsumo)
                .addGap(50, 50, 50))
        );

        jTBPrincipal.addTab("Pedir Consumo", jPConsumo);

        jLabel4.setText("Monto pedido:");

        jLabel6.setText("Numero de tarjeta:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Peticion de avances");

        btnPedirAvance.setText("PEDIR AVANCE");
        btnPedirAvance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedirAvanceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tfMontoAvance)
                                        .addComponent(cbNumeroTarjetaAvance, 0, 189, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(btnPedirAvance)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel9)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbNumeroTarjetaAvance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfMontoAvance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnPedirAvance, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jTBPrincipal.addTab("Pedir Avances", jPanel1);

        jPCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));

        jLabel15.setText("Tipo de documento:");

        jLabel16.setText("Numero de documento:");

        btnBuscarCliente.setText("BUSCAR");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPClienteLayout = new javax.swing.GroupLayout(jPCliente);
        jPCliente.setLayout(jPClienteLayout);
        jPClienteLayout.setHorizontalGroup(
            jPClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPClienteLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPClienteLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(tfNumeroDocumento))
                    .addGroup(jPClienteLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(37, 37, 37)
                        .addComponent(cbTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscarCliente)
                .addGap(18, 18, 18))
        );
        jPClienteLayout.setVerticalGroup(
            jPClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPClienteLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnBuscarCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPClienteLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tfNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTBPrincipal))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jTBPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPedirAvanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedirAvanceActionPerformed
        // TODO add your handling code here:
        try {

        	if(tfMontoAvance.getText().isEmpty()){
				JOptionPane.showMessageDialog(null, "Debe diligenciar todos los datos para hacer el avance");
			}else{
			CreditCardConsume creditConsume = new CreditCardConsume();
			CreditCard credit = (CreditCard) cbNumeroTarjetaPedir.getSelectedItem();
			creditConsume.setPayed(false);
			creditConsume.setCreditCard(credit);
			creditConsume.setInterest(0.036);
			creditConsume.setRemainingAmmount(Double.parseDouble(tfMontoAvance.getText()));
			creditConsume.setAmmount(Double.parseDouble(tfMontoAvance.getText()));
			creditConsume.setNumberShares(24);
			controlador.crearCreditCardConsume(creditConsume);
			controlador.editarCreditCard(credit, Double.parseDouble(tfMontoAvance.getText()));
			JOptionPane.showMessageDialog(null, "Se pidio el avance correctamente");
			}
		} catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
		}
    }//GEN-LAST:event_btnPedirAvanceActionPerformed

	private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBuscarClienteActionPerformed
		// TODO add your handling code here:
		try {
			Customer cus = controladorCus.buscarCustomer((String) cbTipoDocumento.getSelectedItem(),
					tfNumeroDocumento.getText());
			if (cus != null) {

				cargarComboCuentas(cus);
				jTBPrincipal.setVisible(true);

			} else {
				JOptionPane.showMessageDialog(null, "No existe!!!!", "ERROR", JOptionPane.WARNING_MESSAGE);
			}

		} catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
		}

	}// GEN-LAST:event_btnBuscarClienteActionPerformed

	private void btnPedirConsumoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnPedirConsumoActionPerformed
		// TODO add your handling code here:
		try {

			if(tfMontoPedir.getText().isEmpty() || tfNumeroCuotasPedir.getText().isEmpty()){
				JOptionPane.showMessageDialog(null, "Debe diligenciar todos los datos para hacer el consumo");
			}else{
			CreditCardConsume creditConsume = new CreditCardConsume();
			CreditCard credit = (CreditCard) cbNumeroTarjetaPedir.getSelectedItem();
			creditConsume.setPayed(false);
			creditConsume.setCreditCard(credit);
			creditConsume.setInterest(0.036);
			creditConsume.setRemainingAmmount(Double.parseDouble(tfMontoPedir.getText()));
			creditConsume.setAmmount(Double.parseDouble(tfMontoPedir.getText()));
			creditConsume.setNumberShares(Integer.parseInt(tfNumeroCuotasPedir.getText()));
			controlador.crearCreditCardConsume(creditConsume);
			controlador.editarCreditCard(credit, Double.parseDouble(tfMontoPedir.getText()));
			JOptionPane.showMessageDialog(null, "Se pidio el consumo correctamente");
			}
		} catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
		}
	}// GEN-LAST:event_btnPedirConsumoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnPedirAvance;
    private javax.swing.JButton btnPedirConsumo;
    private javax.swing.JComboBox cbNumeroTarjetaAvance;
    private javax.swing.JComboBox cbNumeroTarjetaPedir;
    private javax.swing.JComboBox<String> cbTipoDocumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPCliente;
    private javax.swing.JPanel jPConsumo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTBPrincipal;
    private javax.swing.JTextField tfMontoAvance;
    private javax.swing.JTextField tfMontoPedir;
    private javax.swing.JTextField tfNumeroCuotasPedir;
    private javax.swing.JTextField tfNumeroDocumento;
    // End of variables declaration//GEN-END:variables
}
