/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.ingesoft.standalone.gui.vista;

import java.util.List;

import javax.naming.NamingException;
import javax.swing.JOptionPane;

import co.edu.eam.ingesoft.avanzada.persistencia.entidades.CreditCard;
import co.edu.eam.ingesoft.avanzada.persistencia.entidades.Customer;
import co.edu.eam.ingesoft.avanzada.persistencia.entidades.Franchise;
import co.edu.eam.ingesoft.avanzada.persistencia.entidades.Product;
import co.edu.eam.ingesoft.avanzada.persistencia.entidades.SavingAccount;
import co.edu.eam.ingesoft.standalone.gui.controlador.ControladorVentanaGestionCustomer;
import co.edu.eam.ingesoft.standalone.gui.controlador.ControladorVentanaGestionProductos;

/**
 *
 * @author Richard Vanegas
 */
public class VentanaGestionProductos extends javax.swing.JFrame {

	private ControladorVentanaGestionProductos controlador;
	private ControladorVentanaGestionCustomer controladorCus;

	/**
	 * Creates new form VentanaGestionCreditCard
	 */
	public VentanaGestionProductos() {
		
		initComponents();
		try {
			controlador = new ControladorVentanaGestionProductos();
			controladorCus = new ControladorVentanaGestionCustomer();
			cargarComboTipoDocumento();
			cargarComboFranquicia();

		} catch (NamingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		
	}

	/**
	 * Metodo para cargar el combobox de tipo de documento
	 */
	public void cargarComboTipoDocumento() {
		// for (String lista : TipoDocumentEnum.values()) {
		cbTipoDocumentoCredit.addItem("CEDULA");
		cbTipoDocumentoCredit.addItem("TARJETA DE IDENTIDAD");
		cbTipoDocumentoCredit.addItem("REGISTRO CIVIL");
		cbTipoDocumentoTransaccion.addItem("CEDULA");
		cbTipoDocumentoTransaccion.addItem("TARJETA DE IDENTIDAD");
		cbTipoDocumentoTransaccion.addItem("REGISTRO CIVIL");
		cbTipoDocumentoSaving.addItem("CEDULA");
		cbTipoDocumentoSaving.addItem("TARJETA DE IDENTIDAD");
		cbTipoDocumentoSaving.addItem("REGISTRO CIVIL");

		// }
	}

	/**
	 * Metodo para cargar un combo con todas las franquicias del banco
	 */
	public void cargarComboFranquicia() {
		List<Franchise> franquicias = controlador.listarFranquicia();
		cbFranquisia.addItem("Seleccione una franquicia");
		for (Franchise lista : franquicias) {
			cbFranquisia.addItem(lista);
		}
	}

	/**
	 * Metodo para cargar un combo con todas las cuentas de ahorros de un
	 * cliente en especifico
	 * 
	 * @param c
	 *            cliente por el cual se listaran las cuentas de ahorros
	 */
	public void cargarComboCuentas(Customer c) {
		cbCuentaConsignar.removeAllItems();
		cbCuentaATransferir.removeAllItems();
		cbCuentaTransaccion.removeAllItems();
		cbCuentaRetirar.removeAllItems();
		List<SavingAccount> sav = controlador.listarCuentasCliente(c);
		cbCuentaConsignar.addItem("Seleccione una cuenta");
		cbCuentaATransferir.addItem("Seleccione una cuenta");
		cbCuentaRetirar.addItem("Seleccione una cuenta");
		cbCuentaTransaccion.addItem("Seleccione una cuenta");
		for (SavingAccount lista : sav) {
			cbCuentaTransaccion.addItem(lista);
			cbCuentaRetirar.addItem(lista);
			cbCuentaConsignar.addItem(lista);
			cbCuentaATransferir.addItem(lista);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfTipoDocumentoCredit2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTBPrincipal = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        tfFechaVencimientoCredit = new javax.swing.JTextField();
        tfIdCustomerCredit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfNumeroCredit = new javax.swing.JTextField();
        tfCvc = new javax.swing.JTextField();
        btnCrearCredit = new javax.swing.JButton();
        btnBuscarCredit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tfFechaExpedicionCredit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbTipoDocumentoCredit = new javax.swing.JComboBox();
        cbFranquisia = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        tfMontoCredit = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        tfAmmount = new javax.swing.JTextField();
        tfIdCustomerSaving = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfNumeroSaving = new javax.swing.JTextField();
        btnCrearSaving = new javax.swing.JButton();
        btnBuscarSaving = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tfFechaExpedicionSaving = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfSavingInterest = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cbTipoDocumentoSaving = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        cbTipoDocumentoTransaccion = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tfNumeroDocumentoTransaccion = new javax.swing.JTextField();
        btnBuscarClienteTransaccion = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPConsignar = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        cbCuentaConsignar = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        btnConsignar = new javax.swing.JButton();
        tfAmmountConsignar = new javax.swing.JTextField();
        jPRetirar = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        cbCuentaRetirar = new javax.swing.JComboBox();
        tfAmmountRetirar = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        btnRetirar = new javax.swing.JButton();
        jPTransaccion = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tfMontoTransaccion = new javax.swing.JTextField();
        cbCuentaTransaccion = new javax.swing.JComboBox();
        cbCuentaATransferir = new javax.swing.JComboBox();
        btnTransaccion = new javax.swing.JButton();

        jLabel13.setText("Tipo de documento:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tfFechaVencimientoCredit.setEnabled(false);

        jLabel5.setText("Identificacion cliente:");

        jLabel1.setText("Numero:");

        jLabel2.setText("CVC:");

        tfNumeroCredit.setEditable(false);

        tfCvc.setEditable(false);

        btnCrearCredit.setText("CREAR");
        btnCrearCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCreditActionPerformed(evt);
            }
        });

        btnBuscarCredit.setText("BUSCAR");
        btnBuscarCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCreditActionPerformed(evt);
            }
        });

        jLabel3.setText("Fecha de expedicion:");

        tfFechaExpedicionCredit.setEnabled(false);

        jLabel4.setText("Fecha de vencimiento:");

        jLabel8.setText("Tipo de documento:");

        jLabel14.setText("Franquicia:");

        jLabel20.setText("Monto a pedir:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(btnCrearCredit)
                .addGap(50, 50, 50)
                .addComponent(btnBuscarCredit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(tfFechaExpedicionCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfFechaVencimientoCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel8)
                                .addComponent(jLabel14))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbFranquisia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfIdCustomerCredit)
                                .addComponent(cbTipoDocumentoCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel20))
                            .addGap(50, 50, 50)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfCvc)
                                .addComponent(tfNumeroCredit)
                                .addComponent(tfMontoCredit)))))
                .addGap(196, 196, 196))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbTipoDocumentoCredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfIdCustomerCredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbFranquisia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNumeroCredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfCvc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfMontoCredit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfFechaExpedicionCredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfFechaVencimientoCredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarCredit)
                    .addComponent(btnCrearCredit))
                .addGap(32, 32, 32))
        );

        jTBPrincipal.addTab("Credit Card", jPanel1);

        jLabel6.setText("Identificacion cliente:");

        jLabel7.setText("Numero:");

        tfNumeroSaving.setEditable(false);

        btnCrearSaving.setText("CREAR");
        btnCrearSaving.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearSavingActionPerformed(evt);
            }
        });

        btnBuscarSaving.setText("BUSCAR");
        btnBuscarSaving.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarSavingActionPerformed(evt);
            }
        });

        jLabel9.setText("Fecha de expedicion:");

        tfFechaExpedicionSaving.setEnabled(false);

        jLabel10.setText("Saldo:");

        jLabel11.setText("Interes de cuenta:");

        jLabel12.setText("Tipo de documento:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(btnCrearSaving)
                        .addGap(42, 42, 42)
                        .addComponent(btnBuscarSaving))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfFechaExpedicionSaving, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(79, 79, 79)
                                    .addComponent(tfNumeroSaving, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfAmmount, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfSavingInterest, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(26, 26, 26)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfIdCustomerSaving, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                    .addComponent(cbTipoDocumentoSaving, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cbTipoDocumentoSaving, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfIdCustomerSaving, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfNumeroSaving, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfFechaExpedicionSaving, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfAmmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfSavingInterest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarSaving)
                    .addComponent(btnCrearSaving))
                .addGap(40, 40, 40))
        );

        jTBPrincipal.addTab("Saving Account", jPanel2);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));

        jLabel15.setText("Tipo de documento:");

        jLabel16.setText("Numero de documento:");

        btnBuscarClienteTransaccion.setText("BUSCAR");
        btnBuscarClienteTransaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteTransaccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(tfNumeroDocumentoTransaccion))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(37, 37, 37)
                        .addComponent(cbTipoDocumentoTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscarClienteTransaccion)
                .addGap(18, 18, 18))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnBuscarClienteTransaccion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipoDocumentoTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tfNumeroDocumentoTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel21.setText("Cuenta a consignar:");

        jLabel22.setText("Monto a consignar:");

        btnConsignar.setText("CONSIGNAR");
        btnConsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsignarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPConsignarLayout = new javax.swing.GroupLayout(jPConsignar);
        jPConsignar.setLayout(jPConsignarLayout);
        jPConsignarLayout.setHorizontalGroup(
            jPConsignarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPConsignarLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPConsignarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(jPConsignarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnConsignar)
                    .addComponent(cbCuentaConsignar, 0, 199, Short.MAX_VALUE)
                    .addComponent(tfAmmountConsignar))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        jPConsignarLayout.setVerticalGroup(
            jPConsignarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPConsignarLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPConsignarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(cbCuentaConsignar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPConsignarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(tfAmmountConsignar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btnConsignar)
                .addGap(66, 66, 66))
        );

        jTabbedPane1.addTab("Consignar", jPConsignar);

        jLabel23.setText("Cuenta a retirar:");

        jLabel24.setText("Monto a retirar:");

        btnRetirar.setText("RETIRAR");
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPRetirarLayout = new javax.swing.GroupLayout(jPRetirar);
        jPRetirar.setLayout(jPRetirarLayout);
        jPRetirarLayout.setHorizontalGroup(
            jPRetirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRetirarLayout.createSequentialGroup()
                .addGroup(jPRetirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPRetirarLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPRetirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addGap(18, 18, 18)
                        .addGroup(jPRetirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbCuentaRetirar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfAmmountRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPRetirarLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(btnRetirar)))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPRetirarLayout.setVerticalGroup(
            jPRetirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRetirarLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPRetirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(cbCuentaRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPRetirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(tfAmmountRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(btnRetirar)
                .addGap(44, 44, 44))
        );

        jTabbedPane1.addTab("Retirar", jPRetirar);

        jLabel17.setText("Cuenta:");

        jLabel18.setText("Cuenta a transferir:");

        jLabel19.setText("Monto:");

        btnTransaccion.setText("TRANSFERIR SALDO");
        btnTransaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPTransaccionLayout = new javax.swing.GroupLayout(jPTransaccion);
        jPTransaccion.setLayout(jPTransaccionLayout);
        jPTransaccionLayout.setHorizontalGroup(
            jPTransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTransaccionLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPTransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPTransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbCuentaTransaccion, 0, 151, Short.MAX_VALUE)
                    .addComponent(tfMontoTransaccion))
                .addGroup(jPTransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPTransaccionLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbCuentaATransferir, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19))
                    .addGroup(jPTransaccionLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btnTransaccion)
                        .addContainerGap(92, Short.MAX_VALUE))))
        );
        jPTransaccionLayout.setVerticalGroup(
            jPTransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTransaccionLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPTransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(cbCuentaTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCuentaATransferir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPTransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tfMontoTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTransaccion))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Transaccion", jPTransaccion);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTBPrincipal.addTab("Transacciones", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTBPrincipal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jTBPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRetirarActionPerformed
		// TODO add your handling code here:
		try {

			if (cbCuentaRetirar.getSelectedIndex() == 0) {
				JOptionPane.showMessageDialog(null,
						"Debe seleccionar la cuenta de ahorros de la cual va a retirar el dinero");
			} else if (tfAmmountRetirar.getText().isEmpty()) {
				JOptionPane.showMessageDialog(null, "Debe ingresar el monto a retirar");
			} else {
				SavingAccount sav = (SavingAccount) cbCuentaRetirar.getSelectedItem();
				// sav.setAmmount(sav.getAmmount() -
				// Double.parseDouble(tfAmmountRetirar.getText()));
				controlador.retirarMontoCuenta(sav, Double.parseDouble(tfAmmountRetirar.getText()));
				JOptionPane.showMessageDialog(null, "Se retiro correctamente el dinero de su cuenta de ahorros");
				limpiarCamposConsignar();
			}
		} catch (NumberFormatException e) {
			JOptionPane.showMessageDialog(null, "El monto a retirar debe ser un valor numerico", "ERROR",
					JOptionPane.ERROR_MESSAGE);
		} catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
		}

	}// GEN-LAST:event_btnRetirarActionPerformed

	private void btnConsignarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnConsignarActionPerformed
		// TODO add your handling code here:
		try {

			if (cbCuentaConsignar.getSelectedIndex() == 0) {
				JOptionPane.showMessageDialog(null, "Debe seleccionar la cuenta de ahorros a la cual va a consignar");
			} else if (tfAmmountConsignar.getText().isEmpty()) {
				JOptionPane.showMessageDialog(null, "Debe ingresar el monto que desea consignar");
			} else {
				SavingAccount sav = (SavingAccount) cbCuentaConsignar.getSelectedItem();
				controlador.consignarMontoCuenta(sav,Double.parseDouble(tfAmmountConsignar.getText()));
				JOptionPane.showMessageDialog(null, "Se consigno correctamente el dinero a su cuenta de ahorros");
				limpiarCamposConsignar();
			}
		} catch (NumberFormatException e) {
			JOptionPane.showMessageDialog(null, "El monto a consignar debe ser un valor numerico", "ERROR",
					JOptionPane.ERROR_MESSAGE);
		} catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
		}
	}// GEN-LAST:event_btnConsignarActionPerformed

	private void limpiarCamposConsignar() {

		tfAmmountConsignar.setText(null);
		cbCuentaConsignar.removeAllItems();
		cbCuentaATransferir.removeAllItems();
		cbCuentaTransaccion.removeAllItems();
		cbCuentaRetirar.removeAllItems();
		tfAmmountRetirar.setText(null);
		tfMontoTransaccion.setText(null);
		tfNumeroDocumentoTransaccion.setText(null);

	}

	private void btnTransaccionActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnTransaccionActionPerformed
		// TODO add your handling code here:

		try {

			if (cbCuentaTransaccion.getSelectedIndex() == 0) {
				JOptionPane.showMessageDialog(null,
						"Debe seleccionar la cuenta de ahorros de la cual" + " quiere transferir");
			} else if (cbCuentaATransferir.getSelectedIndex() == 0) {
				JOptionPane.showMessageDialog(null, "Debe seleccionar a la cual va a transferir");
			} else if (cbCuentaTransaccion.getSelectedIndex() == cbCuentaATransferir.getSelectedIndex()) {
				JOptionPane.showMessageDialog(null, "No puede transferir saldo entre la misma cuenta");
			} else if (tfMontoTransaccion.getText().isEmpty()) {
				JOptionPane.showMessageDialog(null, "Debe ingresar el monto a transladar");
			} else {

				SavingAccount savSalida = (SavingAccount) cbCuentaTransaccion.getSelectedItem();
				SavingAccount savEntrada = (SavingAccount) cbCuentaATransferir.getSelectedItem();
				controlador.transladarMontoCuenta(savSalida, savEntrada,
						Double.parseDouble(tfMontoTransaccion.getText()));
				JOptionPane.showMessageDialog(null, "Se consigno correctamente el dinero a su cuenta de ahorros");
				limpiarCamposConsignar();
			}

		} catch (NumberFormatException e) {
			JOptionPane.showMessageDialog(null, "El monto a transladar debe ser un valor numerico", "ERROR",
					JOptionPane.ERROR_MESSAGE);
		} catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
		}

	}// GEN-LAST:event_btnTransaccionActionPerformed

	private void btnBuscarClienteTransaccionActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBuscarClienteTransaccionActionPerformed
		// TODO add your handling code here:
		try {
			if (tfNumeroDocumentoTransaccion.getText().isEmpty()) {
				JOptionPane.showMessageDialog(null, "Debe ingresar el numero de documento del cliente");
			} else {
				Customer cus = controladorCus.buscarCustomer(cbTipoDocumentoTransaccion.getSelectedItem().toString(),
						tfNumeroDocumentoTransaccion.getText());
				if (cus != null) {

					cargarComboCuentas(cus);

				} else {
					JOptionPane.showMessageDialog(null, "No existe!!!!", "ERROR", JOptionPane.WARNING_MESSAGE);
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
		}
	}// GEN-LAST:event_btnBuscarClienteTransaccionActionPerformed

	private void btnCrearCreditActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCrearCreditActionPerformed
		// TODO add your handling code here:

		try {

			if (tfIdCustomerCredit.getText().isEmpty() || tfMontoCredit.getText().isEmpty()
					|| cbFranquisia.getSelectedIndex() == 0) {
				JOptionPane.showMessageDialog(null, "Debe completar todos los campos");
			} else {

				Customer c = controladorCus.buscarCustomer((String) cbTipoDocumentoCredit.getSelectedItem(),
						tfIdCustomerCredit.getText());
				int cant = 0;
				if (c != null) {
					for (Product lista : c.getProductos()) {
						if (lista instanceof CreditCard) {
							cant++;
						}
					}
					if (c.getProductos().size() >= 5) {
						JOptionPane.showMessageDialog(null, "Este cliente ya tiene 5 productos registrados");
					} else if (cant == 2) {
						JOptionPane.showMessageDialog(null, "Este cliente ya tiene 2 tarjetas de credito");
					} else {
						CreditCard credit = new CreditCard();
						credit.setFranchise((Franchise) cbFranquisia.getSelectedItem());
						credit.setCustomer(c);
						credit.setAmmount(Double.parseDouble(tfMontoCredit.getText()));
						credit.setAmmountConsumed(0);
						controlador.crearCreditCard(credit);
						JOptionPane.showMessageDialog(null, "Se creo correctamente la tarjeta de credito");
					}
				} else {
					JOptionPane.showMessageDialog(null, "El customer con numero de identificacion "
							+ tfIdCustomerCredit.getText() + " no esta " + "registrado en el banco");
				}
			}
		} catch (NumberFormatException e) {
			JOptionPane.showMessageDialog(null, "El monto debe ser un valor numerico", "ERROR",
					JOptionPane.ERROR_MESSAGE);
		} catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
		}
	}// GEN-LAST:event_btnCrearCreditActionPerformed

	private void btnBuscarCreditActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBuscarCreditActionPerformed
		// TODO add your handling code here:
		try {

			CreditCard credit = controlador.buscarCreditCard(tfNumeroCredit.getText());
			if (credit != null) {
				tfCvc.setText(credit.getCvc());
				tfFechaExpedicionCredit.setText(credit.getExpeditionDate().getTime() + "");
				tfFechaVencimientoCredit.setText(credit.getExpirationDate().getTime() + "");
				tfIdCustomerCredit.setText(credit.getCustomer().getIdNum());
				cbTipoDocumentoCredit.setSelectedItem(credit.getCustomer().getIdType());
				cbFranquisia.setSelectedItem(credit.getFranchise().getName());
				tfMontoCredit.setText(credit.getAmmount() + "");
			} else {
				JOptionPane.showMessageDialog(null, "No existe!!!!", "ERROR", JOptionPane.WARNING_MESSAGE);
			}

		} catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
		}
	}// GEN-LAST:event_btnBuscarCreditActionPerformed

	private void btnCrearSavingActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCrearSavingActionPerformed
		// TODO add your handling code here:
		try {
			if (tfIdCustomerSaving.getText().isEmpty() || tfAmmount.getText().isEmpty()) {
				JOptionPane.showMessageDialog(null, "Debe completar todos los campos");
			} else {
				Customer c = controladorCus.buscarCustomer((String) cbTipoDocumentoSaving.getSelectedItem(),
						tfIdCustomerSaving.getText());
				if (c != null) {
					if (c.getProductos().size() >= 5) {
						JOptionPane.showMessageDialog(null, "Este cliente ya tiene 5 productos registrados");
					} else {
						SavingAccount saving = new SavingAccount();
						saving.setAmmount(Double.parseDouble(tfAmmount.getText()));
						// saving.setAmmount(0);
						saving.setSavingInterest(Double.parseDouble(tfSavingInterest.getText()));
						saving.setCustomer(c);
						controlador.crearSavingAccount(saving);
						JOptionPane.showMessageDialog(null, "Se creo correctamente la cuenta de ahorros");
					}
				} else {
					JOptionPane.showMessageDialog(null, "El customer con numero de identificacion "
							+ tfIdCustomerCredit.getText() + " no esta " + "registrado en el banco");
				}
			}
		} catch (NumberFormatException e) {
			JOptionPane.showMessageDialog(null, "El monto debe ser un valor numerico", "ERROR",
					JOptionPane.ERROR_MESSAGE);
		} catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
		}

	}// GEN-LAST:event_btnCrearSavingActionPerformed

	private void btnBuscarSavingActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBuscarSavingActionPerformed
		// TODO add your handling code here:
		try {

			SavingAccount sav = controlador.buscarSavingAccount(tfNumeroSaving.getText());
			if (sav != null) {
				tfAmmount.setText(sav.getAmmount() + "");
				tfSavingInterest.setText(sav.getSavingInterest() + "");
				tfFechaExpedicionSaving.setText(sav.getExpeditionDate().getTime() + "");
				tfIdCustomerSaving.setText(sav.getCustomer().getIdNum());
				cbTipoDocumentoSaving.setSelectedItem(sav.getCustomer().getIdType());
			} else {
				JOptionPane.showMessageDialog(null, "No existe!!!!", "ERROR", JOptionPane.WARNING_MESSAGE);
			}

		} catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
		}
	}// GEN-LAST:event_btnBuscarSavingActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarClienteTransaccion;
    private javax.swing.JButton btnBuscarCredit;
    private javax.swing.JButton btnBuscarSaving;
    private javax.swing.JButton btnConsignar;
    private javax.swing.JButton btnCrearCredit;
    private javax.swing.JButton btnCrearSaving;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JButton btnTransaccion;
    private javax.swing.JComboBox cbCuentaATransferir;
    private javax.swing.JComboBox cbCuentaConsignar;
    private javax.swing.JComboBox cbCuentaRetirar;
    private javax.swing.JComboBox cbCuentaTransaccion;
    private javax.swing.JComboBox cbFranquisia;
    private javax.swing.JComboBox<String> cbTipoDocumentoCredit;
    private javax.swing.JComboBox<String> cbTipoDocumentoSaving;
    private javax.swing.JComboBox<String> cbTipoDocumentoTransaccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPConsignar;
    private javax.swing.JPanel jPRetirar;
    private javax.swing.JPanel jPTransaccion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTBPrincipal;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField tfAmmount;
    private javax.swing.JTextField tfAmmountConsignar;
    private javax.swing.JTextField tfAmmountRetirar;
    private javax.swing.JTextField tfCvc;
    private javax.swing.JTextField tfFechaExpedicionCredit;
    private javax.swing.JTextField tfFechaExpedicionSaving;
    private javax.swing.JTextField tfFechaVencimientoCredit;
    private javax.swing.JTextField tfIdCustomerCredit;
    private javax.swing.JTextField tfIdCustomerSaving;
    private javax.swing.JTextField tfMontoCredit;
    private javax.swing.JTextField tfMontoTransaccion;
    private javax.swing.JTextField tfNumeroCredit;
    private javax.swing.JTextField tfNumeroDocumentoTransaccion;
    private javax.swing.JTextField tfNumeroSaving;
    private javax.swing.JTextField tfSavingInterest;
    private javax.swing.JTextField tfTipoDocumentoCredit2;
    // End of variables declaration//GEN-END:variables
}
